title: Composable Connectivity Workshop

# Navigation
nav_external_links:
  - title: Salesforce Workshop Site (original)
    url: https://sites.google.com/salesforce.com/acbworkshop?usp=sharing

# Aux (top-right) links
aux_links:
  "View on GitHub":
    - "https://github.com/anarumanchi-sf/ccworkshop.github.io"
aux_links_new_tab: true

# Footer
footer_content: "© {year} Mulesoft"
